### ISSUE TITLE
Change PB Green 300 Color

### ISSUE THREAD

**Issue by victorhayes** [PBGUX/designsystem#55] opened 2015-12-01 13:49 UTC
Change PB Green 300 to #AAD88F

**Comment by danielcollettepb** [comment] 2015-12-01 14:10
This is a duplicate of [#48](https://github.com/PBGUX/designsystem/issues/48) and will be in the next release

![image](https://cloud.githubusercontent.com/assets/6116867/11502876/5a734cec-980b-11e5-8866-d461d3cbfcba.png)

**Closed by danielcollettepb** 2015-12-01 14:10 UTC
Labels: duplicate
